### ISSUE TITLE
AV while compile BPL on Delphi XE

### ISSUE THREAD

**Issue by rfrezino** [RomanYankovsky/DelphiAST#153] opened 2016-01-22 12:44 UTC
I don't know why, but when I try to compile Delphi AST at a package I get an AV,
[DCC Fatal Error] SimpleParser.Lexer.pas(1): F2084 Internal Error: AV09625F54-R00000003-0.

I got a similar error at OmniThread library, It was a problem with a directive. 

Thanks

**Comment by RomanYankovsky** [comment] 2016-01-22 12:47
Can you post the package source?

**Comment by rfrezino** [comment] 2016-01-22 12:59
Yes, it's here.

https://onedrive.live.com/redir?resid=2ABCC55A73D6DE55!17369&authkey=!AJql4IflM7vsAKg&ithint=folder%2c7z

**Comment by sglienke** [comment] 2016-01-22 13:53
Found the issue - here's the fix:

```delphi

+  TCharProc = procedure of object;
+  TTokenKindFunc = function: TptTokenKind of object;
+
   TmwBasePasLex = class(TObject)
   private
     FCommentState: TCommentState;
-    FProcTable: array[#0..#127] of procedure of object;
+    FProcTable: array[#0..#127] of TCharProc;
     FBuffer: PBufferRec;
     RunAhead: Integer;
     TempRun: Integer;
     BufferSize: integer;
-    FIdentFuncTable: array[0..191] of function: TptTokenKind of object;
+    FIdentFuncTable: array[0..191] of TTokenKindFunc;
     FTokenPos: Integer;
     FTokenID: TptTokenKind;
     FExID: TptTokenKind;

```

**Comment by Wosi** [comment] 2016-01-22 14:10
@sglienke Great catch!
But to be honest: This is not a bug in DelphiAST. It's a compiler bug that should be addressed to Embarcadero.

**Comment by rfrezino** [comment] 2016-01-22 14:16
Very good guys!

**Comment by rfrezino** [comment] 2016-01-22 14:22
Hun... I did a test, it's not working for me yet. :(

http://imgur.com/3WNrl15

**Comment by sglienke** [comment] 2016-01-22 14:22
@Wosi You realize that this happens in a Delphi version released in 2010? Seattle does not have this bug.

**Comment by sglienke** [comment] 2016-01-22 14:26
@rfrezino Then you are not compiling the changed unit or have some dcu lying around. I can confirm that after these changes your package compiles.

**Comment by Wosi** [comment] 2016-01-22 14:32
@sglienke Oops, I didn't see it's related to an old version.

**Comment by uschuster** [comment] 2016-01-22 19:35
This is an old compiler / mwPasLex issue that I've reported as QC 107123 and that affects D2009 till XE3.

[Regression] F2084 Internal Error: AV with enabled HPP creation for nameless procedure array
http://qc.embarcadero.com/wc/qcmain.aspx?d=107123

**Comment by rfrezino** [comment] 2016-01-28 15:59
Yes, you can close it's not a bug of DelphiAST.
I created the find uses using your project: https://github.com/rfrezino/RFindUnit
Thanks!

**Comment by RomanYankovsky** [comment] 2016-01-28 16:21
@rfrezino looks very interesting! :)

**Closed by RomanYankovsky** 2016-01-28 16:21 UTC
Labels: bug
