### ISSUE TITLE
System.Rtti.pas cannot be parsed in Delphi 10.1

### ISSUE THREAD

**Issue by sglienke** [RomanYankovsky/DelphiAST#175] opened 2016-05-03 15:40 UTC
It seems that the conditional define is the cause:

The following unit reproduces the error
```
unit Unit1;

interface

implementation

procedure Test;
{$IF ((Defined(CPUX86) or Defined(CPUX64)) and (Defined(LINUX) or Defined(MSWINDOWS) or Defined(MACOS))) or (Defined(CPUARM) and Defined(LINUX))}
begin
end;
{$ENDIF}

end.
````

**Comment by RomanYankovsky** [comment] 2016-05-03 15:42
Currently complicated IF clauses are not supported. Look at ```TmwBasePasLex.EvaluateConditionalExpression```, it's very primitive. We have to improve that.

**Comment by RomanYankovsky** [comment] 2016-05-03 15:45
Duplicate of https://github.com/RomanYankovsky/DelphiAST/issues/35

**Closed by RomanYankovsky** 2016-05-03 15:45 UTC
Labels: enhancement
